# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dong_core/sensor.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sensor(genpy.Message):
  _md5sum = "2e51394dd57ce1e429a6d473451795f5"
  _type = "dong_core/sensor"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 left_encoder
float64 right_encoder
float64 yaw_angle

bool quest

"""
  __slots__ = ['left_encoder','right_encoder','yaw_angle','quest']
  _slot_types = ['float64','float64','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_encoder,right_encoder,yaw_angle,quest

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sensor, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.left_encoder is None:
        self.left_encoder = 0.
      if self.right_encoder is None:
        self.right_encoder = 0.
      if self.yaw_angle is None:
        self.yaw_angle = 0.
      if self.quest is None:
        self.quest = False
    else:
      self.left_encoder = 0.
      self.right_encoder = 0.
      self.yaw_angle = 0.
      self.quest = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3dB().pack(_x.left_encoder, _x.right_encoder, _x.yaw_angle, _x.quest))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.left_encoder, _x.right_encoder, _x.yaw_angle, _x.quest,) = _get_struct_3dB().unpack(str[start:end])
      self.quest = bool(self.quest)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3dB().pack(_x.left_encoder, _x.right_encoder, _x.yaw_angle, _x.quest))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.left_encoder, _x.right_encoder, _x.yaw_angle, _x.quest,) = _get_struct_3dB().unpack(str[start:end])
      self.quest = bool(self.quest)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3dB = None
def _get_struct_3dB():
    global _struct_3dB
    if _struct_3dB is None:
        _struct_3dB = struct.Struct("<3dB")
    return _struct_3dB
